# Generated by Django 4.2 on 2023-04-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='worry_images/'),
        ),
    ]
